/* <copyright file="ChatHistory.cs" company="PlaceholderCompany">
 * Copyright (c) PlaceholderCompany. All rights reserved.
 * </copyright>
 *
<summary>
This file defines the ChatHistory class, which represents a record of user and AI interactions in the Smart Auto Trader application.
</summary>
<remarks>
The ChatHistory class is used to store and track user messages and AI-generated responses during conversations. It includes metadata such as timestamps and links to the user and conversation session. This class is typically used for analytics, debugging, and improving AI-based recommendations.
</remarks>
<dependencies>
- System.ComponentModel.DataAnnotations
- System.ComponentModel.DataAnnotations.Schema
</dependencies>
 */

namespace SmartAutoTrader.API.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// Represents a record of user and AI interactions during a conversation.
    /// </summary>
    /// <remarks>
    /// This class stores user messages, AI responses, and metadata such as timestamps and session associations.
    /// </remarks>
    public class ChatHistory
    {
        /// <summary>
        /// Gets or sets the unique identifier for the chat history record.
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier of the user associated with this chat history record.
        /// </summary>
        public int UserId { get; set; }

        /// <summary>
        /// Gets or sets the user associated with this chat history record.
        /// </summary>
        /// <remarks>
        /// This property establishes a relationship between the chat history and the user entity.
        /// </remarks>
        [ForeignKey("UserId")]
        public User? User { get; set; }

        /// <summary>
        /// Gets or sets the message sent by the user.
        /// </summary>
        [Required]
        public string UserMessage { get; set; } = null!;

        /// <summary>
        /// Gets or sets the response generated by the AI.
        /// </summary>
        [Required]
        public string AIResponse { get; set; } = null!;

        /// <summary>
        /// Gets or sets the timestamp of when the interaction occurred.
        /// </summary>
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier of the conversation session associated with this chat history record.
        /// </summary>
        public int? ConversationSessionId { get; set; }

        /// <summary>
        /// Gets or sets the conversation session associated with this chat history record.
        /// </summary>
        /// <remarks>
        /// This property establishes a relationship between the chat history and the conversation session entity.
        /// </remarks>
        public virtual ConversationSession? Session { get; set; }
    }
}