/* <copyright file="ChatResponse.cs" company="PlaceholderCompany">
 * Copyright (c) PlaceholderCompany. All rights reserved.
 * </copyright>
 *
<summary>
This file defines the ChatResponse class, which represents the response generated by the AI system during a user conversation in the Smart Auto Trader application.
</summary>
<remarks>
The ChatResponse class encapsulates the AI-generated message, recommended vehicles, updated recommendation parameters, and other metadata such as whether clarification is needed or the matched category. This class is typically used to structure the output of AI-based recommendation services and facilitate communication between the backend and frontend.
</remarks>
<dependencies>
- SmartAutoTrader.API.Models
</dependencies>
 */

namespace SmartAutoTrader.API.Models
{
    /// <summary>
    /// Represents the response generated by the AI system during a user conversation.
    /// </summary>
    /// <remarks>
    /// This class contains the AI-generated message, a list of recommended vehicles, updated recommendation parameters, and metadata such as whether clarification is needed or the matched category.
    /// </remarks>
    public class ChatResponse
    {
        /// <summary>
        /// Gets or sets the AI-generated message to be displayed to the user.
        /// </summary>
        public string? Message { get; set; }

        /// <summary>
        /// Gets or sets the list of vehicles recommended by the AI system.
        /// </summary>
        /// <remarks>
        /// This property contains a list of vehicles that match the user's preferences or query.
        /// </remarks>
        public List<Vehicle> RecommendedVehicles { get; set; } = [];

        /// <summary>
        /// Gets or sets the updated recommendation parameters based on the user's input.
        /// </summary>
        /// <remarks>
        /// This property is used to refine the recommendation process by updating the user's preferences or query parameters.
        /// </remarks>
        public RecommendationParameters? UpdatedParameters { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether clarification is needed from the user.
        /// </summary>
        /// <remarks>
        /// If true, the AI system requires additional input or clarification from the user to proceed with the recommendation.
        /// </remarks>
        public bool ClarificationNeeded { get; set; }

        /// <summary>
        /// Gets or sets the original input provided by the user.
        /// </summary>
        /// <remarks>
        /// This property stores the raw input from the user for reference or debugging purposes.
        /// </remarks>
        public string? OriginalUserInput { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier of the conversation associated with this response.
        /// </summary>
        /// <remarks>
        /// This property links the response to a specific conversation session.
        /// </remarks>
        public string? ConversationId { get; set; }

        /// <summary>
        /// Gets or sets the category that was matched based on the user's input.
        /// </summary>
        /// <remarks>
        /// This property indicates the category or intent identified from the user's input, such as "SUVs" or "Electric Vehicles.".
        /// </remarks>
        public string? MatchedCategory { get; set; }
    }
}