/* <copyright file="ConversationTurn.cs" company="PlaceholderCompany">
 * Copyright (c) PlaceholderCompany. All rights reserved.
 * </copyright>
 *
<summary>
This file defines the ConversationTurn class, which represents a single turn in a conversation between a user and the AI system in the Smart Auto Trader application.
</summary>
<remarks>
The ConversationTurn class is used to encapsulate details about a single interaction in a conversation, including the user's message, the AI's response, and the timestamp of the interaction. This class is typically used for tracking conversation history and facilitating analytics or debugging.
</remarks>
<dependencies>
- None
</dependencies>
 */

namespace SmartAutoTrader.API.Models
{
    /// <summary>
    /// Represents a single turn in a conversation between a user and the AI system.
    /// </summary>
    /// <remarks>
    /// This class encapsulates the user's message, the AI's response, and the timestamp of the interaction.
    /// </remarks>
    public class ConversationTurn
    {
        /// <summary>
        /// Gets or sets the message sent by the user during this conversation turn.
        /// </summary>
        public string UserMessage { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the response generated by the AI during this conversation turn.
        /// </summary>
        public string AIResponse { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the timestamp of when this conversation turn occurred.
        /// </summary>
        /// <remarks>
        /// Defaults to the current UTC time when the object is created.
        /// </remarks>
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    }
}